### ISSUE TITLE
TTY::Editor.open fails when EDITOR has spaces

### ISSUE THREAD

**Issue by technicalpickles** [piotrmurach/tty-editor#1]
### Describe the problem

I'm on macOS and use MacVim for my editor. To make sure it's used everywhere, I set EDITOR to `mvim -f` which opens a new macvim window, and stays in the foreground until the editor closes. This is to keep

`TTY::Editor.open` fails in this case, which makes me think it's because of the space in it.

### Steps to reproduce the problem

```
bundle exec irb -r tty-editor                                                                                                                   5.1s  Thu Aug  8 20:10:23 2019
irb(main):001:0> TTY::Editor.open
TTY::Editor::CommandInvocationError: ` ''` failed with status: 127
	from /Users/technicalpickles/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/tty-editor-0.5.1/lib/tty/editor.rb:205:in `open'
	from /Users/technicalpickles/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/tty-editor-0.5.1/lib/tty/editor.rb:94:in `open'
	from (irb):1
	from /Users/technicalpickles/.rbenv/versions/2.4.4/bin/irb:11:in `<top (required)>'
	from /Users/technicalpickles/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bundler-1.16.4/lib/bundler/cli/exec.rb:74:in `load'
	from /Users/technicalpickles/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bundler-1.16.4/lib/bundler/cli/exec.rb:74:in `kernel_load'
	from /Users/technicalpickles/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bundler-1.16.4/lib/bundler/cli/exec.rb:28:in `run'
	from /Users/technicalpickles/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bundler-1.16.4/lib/bundler/cli.rb:424:in `exec'
	from /Users/technicalpickles/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bundler-1.16.4/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /Users/technicalpickles/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bundler-1.16.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/technicalpickles/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bundler-1.16.4/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
	from /Users/technicalpickles/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bundler-1.16.4/lib/bundler/cli.rb:27:in `dispatch'
	from /Users/technicalpickles/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bundler-1.16.4/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
	from /Users/technicalpickles/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bundler-1.16.4/lib/bundler/cli.rb:18:in `start'
	from /Users/technicalpickles/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bundler-1.16.4/exe/bundle:30:in `block in <top (required)>'
	from /Users/technicalpickles/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bundler-1.16.4/lib/bundler/friendly_errors.rb:124:in `with_friendly_errors'
	from /Users/technicalpickles/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bundler-1.16.4/exe/bundle:22:in `<top (required)>'
	from /Users/technicalpickles/.rbenv/versions/2.4.4/bin/bundle:23:in `load'
	from /Users/technicalpickles/.rbenv/versions/2.4.4/bin/bundle:23:in `<main>'```

### Actual behaviour

```
/Users/technicalpickles/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/tty-editor-0.5.1/lib/tty/editor.rb:205:in `open': ` ''` failed with status: 127 (TTY::Editor::CommandInvocationError)
	from /Users/technicalpickles/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/tty-editor-0.5.1/lib/tty/editor.rb:94:in `open'
	from bin/pretend:94:in `block in <main>'
	from bin/pretend:55:in `loop'
	from bin/pretend:55:in `<main>'
```

### Expected behaviour

Expect a new mvim editor to launch.

### Describe your environment

* OS version: 10.14.5
* Ruby version: 2.4.4p296
* TTY::Editor version: 0.5.1

**Comment by piotrmurach** [comment]
This is fixed in master. The issue was to do with the `which` trying to search for binary `"mvim -f"` instead of `"mvim"` to see if a text editor exists on a system. Failing to do so it would return `nil` which got later expanded to an empty string.
